version: 0.2

phases:
  
  pre_build:
    commands:
      - echo pre build phase...
  build:
    commands:
      - echo Building...
      - mvn clean package
  post_build:
    commands:
      - mv target/*.jar ./    
artifacts:
  files:
    - ./**/*.jar
